# Introduction {#introduction .unnumbered}

Artificial Intelligence (AI) technologies are at the center of academic and public debate. Policymakers around the globe are striving to find strategies that maximize the benefits that such a technological revolution may bring, while at the same time minimizing the negative effects of change. Technological innovation is both seen as a solution to the slowdown in productivity of recent decades and as a danger of increased social tension. At the international level, the US and China are about to launch themselves in a race towards developing autonomous systems to boost their economic and military power, while in 2019 the European Commission headed by von der Leyen relaunched the concept of *"technological sovereignty"*, with the long-term goal of securing strategic autonomy and a greater control of the European digital market. Nevertheless, notwithstanding the importance assigned by policymakers around the globe, technology is the great absent in the analysis of international relations [@herrera2003technology; @herrera2012technology; @weiss2015science]. @herrera2003technology affirms that technology is generally introduced in the analysis in the form of either technological determinism or social constructivism. Technological determinism considers technological change as an exogenous phenomenon: it affects society from outside and enters only to disrupt and alter the equilibrium. Social constructivism instead treats it as a consequence of human agency and interests, and thus it is shaped by cultural, economic, and political forces.

I argue that both of these approaches are correct. Technology is a multidimensional phenomenon that is both exogenous and endogenous. As @Weiss2005ScienceTA suggested, it is tied with international affairs by multiple patterns of interaction. Even if it is indeed true that the development and diffusion of technology are shaped by institutional settings and economic and political forces, it is also true that in many cases, new technologies are the necessary condition for the birth of new institutions and changes in the power distribution of economic and political forces. Technology may influence the dynamics of the international system in the form of an *"escaped genie"* that rapidly spreads along different dimensions of society, prompting a rapid change in the relations between actors on multiple levels, thus creating a fundamental shift in the international system. Often the international community is not able to keep the pace with rapid technological advances, which generate a *"steady stream of new policy issues"* [@weiss2015science] that permeate society, politics, and the economy. At the same time, new technologies may change the international system's dynamics, creating new winners and opening up new areas of conflict while blurring previously clear concepts of international relations theories, such as sovereignty and security. Information and Communication Technologies (ICTs) have increased the speed of economic exchange, increased the ability of firms to operate internationally, and enabled the formation of a platform economy [@kenney2016rise], allowing the rise of digital giants that are not only necessary for the functioning of the market but also have become strong actors in the international setting, influencing policy issues of states of medium dimension, fundamentally changing the distribution of bargaining power between state and non-state actors. Simultaneously, the rate and trajectory of technological innovation are shaped by institutions such as Intellectual Property Rights (IPRs), universities' research agendas, and economic and political competition. Innovation policy here plays a crucial role in determining the rate and direction of technological activity, since its outcomes dynamically alter the distribution of power between the actors of the international arena.

Today, scholars are pointing to Artificial Intelligence as the protagonist of the next great technological revolution, capable of disrupting the economic and power equilibrium both between nations and between states and non-state actors. Economists of innovation define these key enabling technologies as General Purpose Technologies (GPTs), which act as multipliers of change in all aspects of society, economy, and politics, potentially driving waves of technological innovation. GPTs are characterized by being subjected to rapid growth, economic pervasiveness, and strong complementarities with existing and new technologies. Rather than analyzing the international dynamics that will characterize the development of Artificial Intelligence, with the risk of being prone to speculation, in this thesis I adopt a perspective grounded on the economics of innovation to understand why AI technologies are considered the next great revolution in technology, with consequences that can exceed those of ICTs both in scope and length.

Chapter one is focused on introducing AI technologies. Several problems occur when trying to define AI, above all, the problem of defining what intelligence is in the first place. Part of the mainstream debate of the AI field is presented, such as the distinction between Artificial Narrow Intelligence (ANI), a system designed to perform a limited and very specific task, and Artificial General Intelligence (AGI), a system that can perform a variety of different tasks with originality, capable of autonomously identifying problem and solution. While the development of ANI is a well-established practice in the AI community, scholars do not envision that AGI can be reached in the short-medium term, and some even affirm that it is not possible at all. The economic community considers contemporary AI as a merely improvement in *prediction technologies* [@agrawal2018prediction], an essential component in the decision-making process. Treating AI as prediction is essential to understand why this technology can be applied in a variety of fields, and thus why AI should be considered as a General Purpose Technology. This is followed by the presentation of a brief history of AI, from their initial formulation in the 1940s to the more recent developments, with the business success of machine learning and deep learning, distinguishing between symbolic systems, such as expert systems, and sub-symbolic systems, such as machine learning. Finally, the chapter focuses on some functional applications of AI, aimed at presenting some of its broad range of applications and limitations.

As @Drezner2019TechnologicalCA affirmed, much international relations scholarship treats technology as an exogenous shock, an independent variable that changes the dynamics of international politics, shifting the balance of power between one pole to another. However, this perspective does not consider that this relationship works both ways, with specific institutional settings affecting the direction and rate of R&D efforts, influencing the trajectory and the pace of innovation. Chapter two focuses on policy tools that favor or discourage innovation: Intellectual Property Rights (IPRs). Several reasons were proposed to justify the existence of IPRs, either philosophical, such as the natural rights argument and the desert argument, or economical, such as the utilitarian argument. With the awareness that IPRs impose strong externalities on the economy, a consensus was reached within the academic community that the introduction of IPRs makes sense only when they increase the economic welfare. This perspective has the advantage that does not take for granted the introduction of a monopoly right, as temporary as it may be. Unfortunately, the construction of the legal framework surrounding IPRs did not always take into account this perspective, and in many cases was influenced by outsider interests and by the cumulative evolution of legislation. Nevertheless, the economic analysis treats IPRs as a tool to incentivize innovation by awarding a temporary monopoly right to the innovator, striking a balance between society's dynamic economic welfare (that is more well-off if an innovation has taken place) and the static economic welfare (that decreases after the introduction of a monopoly right). In the second part of the chapter, the three IPRs involved with AI will be presented. While the main focus will be on patents (to pose the basis for the empirical analysis of chapter three, copyright and the database sui generis right will also be treated. The remaining part of the chapter focuses on whether it makes sense to introduce additional IPRs specific of AI technologies. This reflection is needed because many legal scholars argued in favor of creating additional IPRs to box AI technologies and their by-products in current legislation. I argue that there is no economic evidence for such action, except in very limited and circumscribed cases, since it would decrease the economic welfare. Moreover, this would lead to the creation of a paradoxical situation where the technologies have to adapt to the challenges of dealing with an over-complex legislation and not the opposite. Altering the current legal framework of innovation would impose changes to an environment that has no need for incentives for innovation, potentially hindering current incentives and slowing down economic growth.

The third chapter focuses on how AI technologies will impact the innovation process and the economics of innovation. First, a theoretical framework surrounding the classification of technologies in different classes will be presented. *General Purpose Technologies* (GPT) will be analyzed in detail, since they have a broad impact on the economy, providing econometric models that describe the dynamics of important externalities caused by innovation complementarities. GPTs are generally considered the origin of virtuous cycles of innovation, in which innovations in one application sector leads to an increase in the rate of innovation in other contingent sectors, where coordination acts as an enhancing factor. Another important categorization is the one first formulated by @griliches1957hybrid, of *Invention of a Method of Inventing* (IMI), which is the invention of a new technique for achieving scientific discoveries or technical innovations, which increase the productivity of R&D departments. The existence of technologies that can be classified as both GPT and IMIs has led the literature to draft a new category: *General Methods of Inventing*, that can be used to define a technology that has both functional applications and research capabilities across a large number of fields. These technologies are extremely rare, the literature agrees that digital computing and, possibly, AI may be classified as such. However, even if there is an agreement on the fact that GMIs have a deep economic impact, their inner dynamics are still unknown. The second part of the chapter will be focused on providing qualitative evidence regarding whether Artificial Intelligence should be considered a GPT (or even a GMI), exploring whether AI possess the three characteristics of GPTs (rapid growth, pervasiveness, and strong complementarities), and its role in the contemporary research process. The use of AI technologies for research and discovery is treated in detail, with a focus on the advantages of Machine Learning for theoretical modeling. Finally, the chapter concludes by examining some of the impacts that AI technologies have on market structure. The digital market is characterized by extreme returns to scale and strong network effects, which give rise to the economies of scope that provide an competitive advantage to incumbents, especially in terms of innovative capabilities. While this has beneficial effects on innovation, it also provides enormous prescriptive power on the way it is conducted and its direction, accentuating the process of market concentration, as suggested by @cremer2019competition. Moreover, the use of AI technologies in the market has several negative externalities, that favor producers over consumer, while creating new issue areas for regulatory authorities, such as algorithmic collusion.

Chapter four is centered around finding quantitative evidence in patent data regarding the technological categorization of Artificial Intelligence as a GPT and the process of market concentration. First, the literature on empirical analysis of GPTs and AI will be reviewed in detail, in particular the one regarding the strategies used for identifying AI-related patents and the indexes used to measure the General Purpose properties of a technology. To this end, I sampled the 2018 edition of PATSTAT, the Worldwide Patent Statistical Database maintained by the European Patent Office. I examined all patent applications filed through the Patent Cooperation Treaty procedure and I identified the AI-related patents by means of a mixed strategy based on both technological classification codes and keyword search. The first part of the analysis focuses on exploring different GPT indicators, both coming from the literature and innovative approaches based on network science. The use of network-based indicators was based on the theoretical modeling of technology evolution provided by @Korzinov2016PervasiveEG, that considers a GPT a technology that is complementary to other technologies based on the number of cliques that it manages to be part of. The results of the analysis confirm that AI should be considered a GPT, since it is rapidly spreading in many areas of the economy and connecting with a range of different technologies to produce new products. The second part of the analysis is instead focused on verifying the claim of chapter three regarding the progressive concentration of AI-related patents in the portfolios of a small number of applicants. AI-related patents were broken down by filing year and the applicants were divided in asymmetrical classes to distinguish between strong and weak patentees, confirming that the proportion of patents filed by strong patentees is increasing, while weak patentees are becoming less and less relevant in patenting activity.

Proof that AI is indeed a GPT increases the evidence that this technology will have a profound impact on society, altering the already fragile dynamics between actors at all levels, from local to international. The most visible consequences will likely regard its effects on employment, and the concentration of property assets involving AI technologies would reduce the capabilities of unemployed workers without providing them the possibility to compete with incumbents. Given their general purposeness, imposing temporary monopolies on the use of such technologies risk of impeding the innovative abilities of new entrants. Rather than proposing new IPRs to explicitly target AI technologies, legal scholars should focus on deescalating the universe of IP regimes that hinder the dynamic AI market, favoring SMEs over oligopolies to reduce the negative externalities provoked by digital giants, which too often dodge responsibility, lack in transparency, and provide no effective opportunity of representation to their clients, while having a normative power comparable (and, in some cases, superior) to the one of states. We are at the dawn of the AI technological revolution and the rate of change is only going to increase.
